### ISSUE TITLE
Introduzione di flowchart per la finanza personale

### ISSUE THREAD

**Issue by corradopetrelli** [emish89/italiapersonalfinance#111]
**Descrizione**

Riferito a: https://www.reddit.com/r/ItaliaPersonalFinance/comments/197zlc7/comment/ki4r7sx nello specifico a questa immagine, https://i.imgur.com/BfHzwr9.png

Questa issue è per discutere di come poter creare il flowchart corrispettivo per l'Italia scrivendo il tutto in [MermaidJS](https://mermaid.js.org/) così da poterlo modificare in futuro mediante la sintassi fornita da mermaid, un piccolo esempio:

```mermaid
graph TB
    sq[Square shape] --> ci((Circle shape))

    subgraph A
        od>Odd shape]-- Two line<br/>edge comment --> ro
        di{Diamond with <br/> line break} -.-> ro(Rounded<br>square<br>shape)
        di==>ro2(Rounded square shape)
    end

    %% Notice that no text in shape are added here instead that is appended further down
    e --> od3>Really long text with linebreak<br>in an Odd shape]

    %% Comments after double percent signs
    e((Inner / circle<br>and some odd <br>special characters)) --> f(,.?!+-*ز)

    cyr[Cyrillic]-->cyr2((Circle shape Начало));

     classDef green fill:#9f6,stroke:#333,stroke-width:2px;
     classDef orange fill:#f96,stroke:#333,stroke-width:4px;
     class sq,e green
     class di orange
```

Cosa pensate possa mancare/si possa modifcare sul flowchart?

**Comment by emish89** [comment]
ciao, inizio a buttare giù qualche idea alla veloce:

1) la struttura base a 5 step mi piace. Diciamo che, riprendendo la wiki, per l'Italia potrebbe essere tipo:

Step 0 : sopravvivenza
Step 1: costruzione fondo emergenza
Step 2: Investimento a breve termine / liquido
Step 3: Investimento a medio termine programmato (casa/auto...)
Step 4: Investimenti di lungo termine

Che ne dici? Per gli step ci penso ma rispetto a quelle UK e US farei molto meno focus sul debito

**Comment by emish89** [comment]
ciao @corradopetrelli per caso hai novità su questo?

**Comment by marcodestefano** [comment]
@emish89 @corradopetrelli  io uno step sui debiti lo terrei comunque: siamo sicuri abbia senso iniziare ad investire a breve/medio/lungo termine se nel frattempo ti stai facendo spennare da eventuali finanziamenti a tassi "elevati"?
Ci metterei anche una parte relativa alle assicurazioni vita, rc, casa... (chiaramente opzionali) perché temo sia sottovalutata. 

Li vedo così:

Step 0 : sopravvivenza
Step 1: assicurare la "stabilità". Lo vedo prima di step 2 perché queste assicurazioni lavorano ad un ordine di grandezza maggiore di quello del fondo di emergenza.
Step 2: costruzione fondo emergenza
Step 3: rimborso debiti ad interessi medio/alti
Step 4: Investimento a breve termine / liquido
Step 5: Investimento a medio termine programmato (casa/auto...)
Step 6: Investimenti di lungo termine
Step 7: fun money? 😃 

Che ne pensate?

**Comment by emish89** [comment]
ciao @marcodestefano , grazie per esserti unito alla discussione! 

Per le assicurazioni per me ci può anche stare come idea opzionale ma diventa molto personale sapere di che assicurazioni uno abbia bisogno. Secondo me andiamo allo step tra il 5 e il 6 per intenderci, ci pensi prima di investire a lungo termine e non prima del fondo di emergenza :)

Per il resto si, partendo dal grafico Inglese come tipologia, secondo me si potrebbe fare con quegli step.

Open to discussion ovviamente!

**Comment by marcodestefano** [comment]
@emish89 grazie a te per gli spunti! Sulla questione opzionalità stavo per scriverlo, ma poi ho pensato possa valere quasi per tutto: potrei non avere necessità di investire a breve, medio o lungo termine in base alla situazione personale (ad esempio se non ho spese previste/pianificate nel breve, o se ho una situazione che non mi permette di pianificare ancora a lungo termine)

Pur rimanendo opzionale la questione assicurativa, l’avrei vista come prima del fondo di emergenza per come interpreto gli step: dal più ”difensivo” al più “aggressivo”: ha senso mettere 6 (o 12, o 24…) mesi di fondo di emergenza da parte ma non avere un’assicurazione sulla casa? O una sulla vita qualora altri dipendano dal tuo reddito? Li vedo come eventi catastrofici che un fondo di emergenza difficilmente può mitigare. Questo vale probabilmente solo su queste due assicurazioni, tutto il resto lo considererei come te più in avanti negli step - o forse a quel punto lo ometterei completamente: rinominerei step 1 come protezione del nucleo familiare - poi chiaramente, se non hai una casa di proprietà o se non hai persone del nucleo che dipendono dal tuo reddito, skip (così come per qualsiasi altro punto?)

Ho un bias relativo ai rischi? O può aver senso quello che sto dicendo?

A prescindere, vedo se nei prossimi giorni riesco a buttare giù la struttura del grafico in base ai vostri input :)

**Comment by emish89** [comment]
@marcodestefano ho buttato su una base su cui lavorare, dacci un occhio quando riesci!
https://github.com/emish89/italiapersonalfinance/blob/main/src/content/charts/flowchart.mermaid

è solo la base mermaid, contenuti open to discussion

**Comment by marcodestefano** [comment]
@emish89 non apro ancora una PR ma dimmi che ne pensi di questa aggiunta per lo step 1:

flowchart LR

    subgraph A[0 - Sopravvivenza]
    direction TB
    stepA1[Start]
    -->
    stepA2("`L'obiettivo è creare un **cashflow positivo**, quindi avere ingressi mensili superiori alle spese`")
    -->
    stepA3("`**Inizia a tracciare le spese** #13;#13;E' importante sapere dove stanno andando i soldi che escono`")
    -->
    stepA4("`Cerca di iniziare a capire se le spese sono ottimizzabili (o se puoi aumentare le entrate)`")
    -->
    |Opzionale| optA5("`Crea un piccolo fondo con 1 mese di spese`") --> stepA6
    stepA4-->stepA6
    stepA6("`Quando arrivi qui vuol dire che riesci a sopravvivere e puoi pensare agli step successivi`")
    end

    subgraph B[1 - Protezione]
    direction TB
    stepB1("`Accumula i risparmi fino ad avere un **Fondo di emergenza** di 3-6 mesi di spese se sei un lavoratore dipendente con contratto stabile, o fino a 12 se sei un libero professionista, in modo da essere tranquillo negli imprevisti`")
    -->
    stepB2("`Valuta la sottoscrizione di un'assicurazione per proteggere la tua casa, se quella in cui vivi è di tua proprietà, e un'assicurazione sulla vita se il tuo nucleo familiare dipende dal tuo reddito`")
    -->
    stepB3("`Valuta di rimborsare tutti i debiti ad alto tasso di interesse, cioè con tasso di interesse maggiore di €STR, che hai contratto. Inizia da quelli a tasso di interesse più alto, prosegui finché non ne hai più.`")
    -->
    stepB4("`Se il tuo contratto lavorativo lo prevede, aderisci al fondo pensione negoziale versando il minimo per ottenere il contributo del datore di lavoro`")
    -->
    |Opzionale| optB5("`Se hai una RAL >50k€ valuta di effettuare ulteriori versamenti al fondo pensione fino a raggiungere il massimo deducibile di 5.164,57€  `")
    -->
    stepB6("`Quando arrivi qui vuol dire che sei al sicuro da imprevisti a breve, medio e lungo termine e puoi pensare agli investimenti`")
    stepB4-->stepB6
    end

    subgraph C[2- Investimenti a breve termine/liquidi]
    direction TB
    stepC1
    end

    subgraph D[3 - Investimenti a medio termine]
    direction TB
    stepD1
    end

    subgraph E[4 - Investimenti a lungo termine]
    direction TB
    stepE1
    end    

    A-->B
    B-->C
    C-->D
    D-->E

**Comment by marcodestefano** [comment]
@emish89  ho creato una pr qui con un po' di dettagli in più sui vari step - sorry sono da browser e sto usando i codespaces: #302

**Comment by emish89** [comment]
grande, sicuro avrò qualche commento quando riuscirò a vederla ma userei la PR a questo punto. Qui chiudo
