### ISSUE TITLE
TradingView data - homepage

### ISSUE THREAD

**Issue by emish89** [emish89/italiapersonalfinance#117]
Ho inserito un widget di TradingView che fornisce dei valori di base sull'andamento della borsa.

Vi piace come idea o secondo voi è da rimuovere?

Fatemi sapere le vostre opinioni, qui l'immagine di cosa ho inserito 

<img width="1856" alt="Screenshot 2024-01-19 at 11 00 00" src="https://github.com/emish89/italiapersonalfinance/assets/27359947/35815b31-24c6-4f94-a0df-483a5784a841">

PS:
Tramite TradingView è possibile inserire gratuitamente vari widget, però nel caso farei una pagina apposita e non li metterei nella home.

**Comment by Uaitt** [comment]
A me piace 👍 💯

**Comment by Uaitt** [comment]
L' unica cosa che forse mi lascia un po' perplesso è che i prezzi sono tutti in dollari mi sembra di capire :thinking:. O sbaglio?

**Comment by emish89** [comment]
> L' unica cosa che forse mi lascia un po' perplesso è che i prezzi sono tutti in dollari mi sembra di capire 🤔. O sbaglio?

dipende dal mercato, sp500 è in dollari, VWCE essendo mercato europeo è in euro etc. Cosa hai visto di errato?

**Comment by Uaitt** [comment]
@emish89 Scusa se rispondo solo ora. Sinceramente non so neanche io che cosa volevo dire, mi sono sicuramente sbagliato (ero fuso probabilmente) 🤦.

Una cosa però forse metterei BTCEUR al posto di BTCUSD, quello sì, però non so se sia possibile :)
