### ISSUE TITLE
Introduce logo

### ISSUE THREAD

**Issue by corradopetrelli** [emish89/italiapersonalfinance#19]
**Description**

Introduce website logo instead of Astro slug 

**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
/

**Additional context**
/

**Comment by emish89** [comment]
what about this one @corradopetrelli ? 
https://github.com/emish89/italiapersonalfinance/blob/main/src/assets/ipf.jpg

**Comment by emish89** [comment]
I added it for now

**Comment by corradopetrelli** [comment]
For now it's fine
