### ISSUE TITLE
Button text on card is wrapped

### ISSUE THREAD

**Issue by corradopetrelli** [emish89/italiapersonalfinance#21]
**Describe the bug**

Text on card button is wrapped

**Screenshots**

![image](https://github.com/emish89/italiapersonalfinance/assets/36475130/c5599913-3b53-4446-923c-cda0a0d1773e)

**Additional context**

Width display: 1200px
Height display: 850px

**Comment by emish89** [comment]
should be fixed with this https://github.com/emish89/italiapersonalfinance/commit/b5123a9e6addc9a0b12bf1d27ada374ae8fb8d50

**Comment by corradopetrelli** [comment]
I confirm it, thanks!
