### ISSUE TITLE
Esempio vendita oro fisico (da investimento) per compensare minusvalenze (reg. dichiarativo)

### ISSUE THREAD

**Issue by marcoredz** [emish89/italiapersonalfinance#384]
Stavo pensando se fosse utile aggiungere un breve paragrafo nella sezione tassazioni riguardo questa possibilità che secondo me non è molto conosciuta, ovvero:

Se si possiede dell'oro fisico da investimento e lo si vende, se si hanno delle minusvalenze gestite in regime dichiarativo, quest'ultime possono essere compensate attraverso la vendita dell'oro fisico.

Penso ad una gran parte di persone che ha oro fisico da investimento magari dalla nascita e che molto probabilmente non avrà mai un certificato di acquisto. Quindi non avendo prezzo di acquisto, dal 2024 paga il 26% di plusvalenza sull'intero importo venduto. Le minusvalenze in questo caso potrebbero alleviare il dolore di pagare il 26% sul totale venduto.

**Comment by emish89** [comment]
ciao, scusa per il ritardo ma me l'ero completamente perso.
attualmente non c'è una vera e propria pagina sull'oro o materie prime ma se ti va di scrivere qualcosa si potrebbe assolutamente aggiungere.
Se no, si potrebbe mettere nel capitolo delle compensazioni plus e minus generiche

**Comment by marcoredz** [comment]
Sì, io pensavo di modificare la pagina delle compensazioni delle minus. Sull'oro in generale no perché non mi reputo esperto, anche se si potrebbe cominciare a creare una sezione raccogliendo le varie informazioni dei vari post del subreddit a riguardo. Per ora comincio con questa modifica lato minusvalenze.
