### ISSUE TITLE
La parola minuti nel tempo di lettura dovrebbe essere dinamica

### ISSUE THREAD

**Issue by Uaitt** [emish89/italiapersonalfinance#77]
**Describe the bug**

la parola *minuti*, in cima ad ogni articolo sul tempo di lettura, dovrebbe avere l' ultima lettera dinamica.

**Minimal example**
Introduzione alla wiki:

![Screenshot from 2023-12-22 13-43-21](https://github.com/emish89/italiapersonalfinance/assets/97030518/173d2b11-1574-4ebe-a05b-c911a6666b3a)

**Expected behavior**
Quando il tempo di lettura è 1 minuto, dovrebe esserci scritto appunto 1 minuto.

**Screenshots**
Vedi sopra.

**Additional context**
Il problema sta [qui](https://github.com/emish89/italiapersonalfinance/blob/main/src/components/blog/BlogContent.astro#L33), ma non avendo esperienza con molta JavaScript forse è meglio che lasci che lo risolva qualcun' altro.

**Comment by emish89** [comment]
fixato qui: https://github.com/emish89/italiapersonalfinance/commit/2a189e1b721a2f7eec907e736b0fb8d3c05251f1
